import type { Product } from "./products";

const now = "2026-07-27T00:00:00.000Z";

export const defaultProducts: Product[] = [
  {
    id: "runa-cheese-burger",
    type: "main",
    title: "Runa cheese burger",
    subtitle: "Simple - 1 medallon",
    description: "Pan brioche, medallon 120g, doble cheddar. Acompanada de papas sazonadas.",
    price: 9499,
    imageKey: "cheeseBurger",
    hasOptions: true,
    optionsTitle: "Elegi cantidad de medallones",
    available: true,
    hidden: false,
    sortOrder: 10,
    createdAt: now,
    updatedAt: now,
    options: [
      { id: "runa-cheese-burger-simple", name: "Simple", subtitle: "Simple - 1 medallon", price: 9499, imageKey: "cheeseBurger", sortOrder: 10 },
      { id: "runa-cheese-burger-doble", name: "Doble", subtitle: "Doble - 2 medallones", price: 11999, imageKey: "cheeseBurgerDoble", sortOrder: 20 },
      { id: "runa-cheese-burger-triple", name: "Triple", subtitle: "Triple - 3 medallones", price: 14499, imageKey: "cheeseBurgerTriple", sortOrder: 30 },
    ],
  },
  {
    id: "runa-bacon",
    type: "main",
    title: "Runa Bacon",
    subtitle: "Simple - 1 medallon",
    description: "Pan brioche, medallon 120g, doble cheddar, bacon crujiente. Acompanada de papas sazonadas.",
    price: 11500,
    imageKey: "bacon",
    hasOptions: true,
    optionsTitle: "Elegi cantidad de medallones",
    available: true,
    hidden: false,
    sortOrder: 20,
    createdAt: now,
    updatedAt: now,
    options: [
      { id: "runa-bacon-simple", name: "Simple", subtitle: "Simple - 1 medallon", price: 11500, imageKey: "bacon", sortOrder: 10 },
      { id: "runa-bacon-doble", name: "Doble", subtitle: "Doble - 2 medallones", price: 14000, imageKey: "baconDoble", sortOrder: 20 },
      { id: "runa-bacon-triple", name: "Triple", subtitle: "Triple - 3 medallones", price: 16500, imageKey: "baconTriple", sortOrder: 30 },
    ],
  },
  {
    id: "runa-tiwaz",
    type: "main",
    title: "Runa Tiwaz",
    description: "Pan brioche, doble medallon 120g, provoleta crugiente, cebolla y morron salteado, cebolla crispy, bacon y salsa bbq. Acompanada de papas sazonadas.",
    price: 16799,
    imageKey: "tiwaz",
    hasOptions: false,
    options: [],
    available: true,
    hidden: false,
    sortOrder: 30,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "runa-gebo",
    type: "main",
    title: "Runa Gebo",
    description: "Pan brioche, medallon 120g, doble cheddar, cebolla crispy, pepinillos agridulces y salsa mil islas. Acompanada de papas sazonadas.",
    price: 16799,
    imageKey: "gebo",
    hasOptions: false,
    options: [],
    available: true,
    hidden: false,
    sortOrder: 40,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "runa-kenaz",
    type: "main",
    title: "Runa Kenaz",
    description: "Pan brioche, doble medallon 120g, provoleta crugiente, morron asado, aros de cebolla y salsa bbq. Acompanada de papas sazonadas.",
    price: 17699,
    imageKey: "kenaz",
    hasOptions: false,
    options: [],
    available: true,
    hidden: false,
    sortOrder: 50,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "runa-raido",
    type: "main",
    title: "Runa Raido",
    description: "Pan brioche, medallon 120g, queso tybo, queso azul, cebolla caramelizada y rucula. Acompanada de papas sazonadas.",
    price: 14999,
    imageKey: "raido",
    hasOptions: false,
    options: [],
    available: true,
    hidden: false,
    sortOrder: 60,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "runa-wunjo",
    type: "main",
    title: "Runa Wunjo",
    description: "Pan brioche, medallon 120g, doble cheaddar, lechuga, cherrys confitados y salsa alioli. Acompanada de papas sazonadas.",
    price: 15990,
    imageKey: "wunjo",
    hasOptions: false,
    options: [],
    available: true,
    hidden: false,
    sortOrder: 70,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "runa-sowilo",
    type: "main",
    title: "Runa Sowilo",
    description: "Pan brioche, doble medallon 120g, triple cheddar, cebolla caramelizada, cebolla crispy, huevo a la plancha, bacon crujiente y mostaza honey. Acompanada de papas sazonadas.",
    price: 18599,
    imageKey: "sowilo",
    hasOptions: false,
    options: [],
    available: true,
    hidden: false,
    sortOrder: 80,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "runa-berka",
    type: "main",
    title: "Runa Berka",
    description: "Pan brioche, medallon 120g, doble cheddar, cebolla caramelizada, bastones de muzza, salsa bbq. Acompanada de papas sazonadas.",
    price: 17699,
    imageKey: "berka",
    hasOptions: false,
    options: [],
    available: true,
    hidden: false,
    sortOrder: 90,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "runa-manaz",
    type: "main",
    title: "Runa Manaz",
    description: "Pan brioche, medallon 120g oklahoma, provoleta crujiente, lechuga, cherrys confitados y huevo a la plancha. Acompanada de papas sazonadas.",
    price: 17800,
    imageKey: "manaz",
    hasOptions: false,
    options: [],
    available: true,
    hidden: false,
    sortOrder: 100,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "runa-pollo-crispy",
    type: "main",
    title: "Runa Pollo Crispy",
    description: "Pan brioche, pollo crispy, lechuga, cherrys confitados y salsa mil islas. Acompanada de papas sazonadas.",
    price: 15899,
    imageKey: "crispy",
    hasOptions: false,
    options: [],
    available: true,
    hidden: false,
    sortOrder: 110,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "picada-runa",
    type: "main",
    title: "Picada Runa",
    description: "Nuggets de pollo x6, Aros de cebolla x6, Bocaditos de espinaca y queso x6, Bastones de muzzarella x6 y Doble porcion de papas sazonadas.",
    price: 20000,
    imageKey: "picadaGebo",
    hasOptions: false,
    options: [],
    available: true,
    hidden: false,
    sortOrder: 120,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "bastones-de-muzza-runa",
    type: "main",
    title: "Bastones de Muzzarella Runa",
    description: "Crujientes bastones de muzzarella x6.",
    price: 7500,
    imageKey: "bastonesDeMuzza",
    hasOptions: false,
    options: [],
    available: true,
    hidden: false,
    sortOrder: 130,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "aros-de-cebolla-runa",
    type: "main",
    title: "Aros de cebolla Runa",
    description: "Crujientes aros de cebolla x6.",
    price: 5500,
    imageKey: "arosDeCebolla",
    hasOptions: false,
    options: [],
    available: true,
    hidden: false,
    sortOrder: 140,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "papas-runa",
    type: "main",
    title: "Papas Runa",
    description: "Papas fritas en una cremosa salsa de queso cheddar, con cebolla de verdeo y panceta.(para compartir).",
    price: 12000,
    imageKey: "papasRuna",
    hasOptions: false,
    options: [],
    available: true,
    hidden: false,
    sortOrder: 150,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "bocaditos-de-pollo-runa",
    type: "main",
    title: "Nuggets de pollo Runa",
    description: "Crujientes nuggets de pollo x6.",
    price: 5500,
    imageKey: "bocaditosPollo",
    hasOptions: false,
    options: [],
    available: true,
    hidden: false,
    sortOrder: 160,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "bocaditos-de-espinaca-runa",
    type: "main",
    title: "Bocaditos de espinaca Runa",
    description: "Crujientes bocaditos de espinaca y queso x6.",
    price: 6000,
    imageKey: "bocaditosEspinaca",
    hasOptions: false,
    options: [],
    available: true,
    hidden: false,
    sortOrder: 170,
    createdAt: now,
    updatedAt: now,
  },
  { id: "bebida-coca-600", type: "drink", title: "COCA 600cc", price: 2500, hasOptions: false, options: [], available: true, hidden: false, sortOrder: 210, createdAt: now, updatedAt: now },
  { id: "bebida-coca-zero-600", type: "drink", title: "COCA Zero 600cc", price: 2500, hasOptions: false, options: [], available: true, hidden: false, sortOrder: 220, createdAt: now, updatedAt: now },
  { id: "bebida-stella-473", type: "drink", title: "Cerveza Stella Artois 473cc", price: 3500, hasOptions: false, options: [], available: true, hidden: false, sortOrder: 230, createdAt: now, updatedAt: now },
  { id: "bebida-amstel-473", type: "drink", title: "Cerveza Amstel Lager rubia 473cc", price: 3500, hasOptions: false, options: [], available: true, hidden: false, sortOrder: 240, createdAt: now, updatedAt: now },
  { id: "bebida-corona-330", type: "drink", title: "Cerveza Corona porron 330cc", price: 3500, hasOptions: false, options: [], available: true, hidden: false, sortOrder: 250, createdAt: now, updatedAt: now },
  { id: "bebida-andes-roja-473", type: "drink", title: "Cerveza Andes Roja 473cc", price: 3500, hasOptions: false, options: [], available: true, hidden: false, sortOrder: 260, createdAt: now, updatedAt: now },
  { id: "bebida-andes-ipa-473", type: "drink", title: "Cerveza Andes IPA Andina 473cc", price: 3500, hasOptions: false, options: [], available: true, hidden: false, sortOrder: 270, createdAt: now, updatedAt: now },
  { id: "bebida-quilmes-stout-473", type: "drink", title: "Cerveza Quilmes Stout 473cc", price: 3500, hasOptions: false, options: [], available: true, hidden: false, sortOrder: 280, createdAt: now, updatedAt: now },
  { id: "extra-tasty-runa", type: "extra", title: "Tasty Runa", description: "Mayonesa ahumada con pickles.", price: 2500, hasOptions: false, options: [], available: true, hidden: false, sortOrder: 310, createdAt: now, updatedAt: now },
  { id: "extra-mayochimi-runa", type: "extra", title: "Mayochimi Runa", description: "Mayonesa con chimichurri.", price: 2500, hasOptions: false, options: [], available: true, hidden: false, sortOrder: 320, createdAt: now, updatedAt: now },
  { id: "extra-bbq-jack-runa", type: "extra", title: "BBQ Jack Runa", description: "Barbacoa con reduccion de wisky.", price: 2500, hasOptions: false, options: [], available: true, hidden: false, sortOrder: 330, createdAt: now, updatedAt: now },
  { id: "extra-big-runa", type: "extra", title: "BIG Runa", description: "Salsa mil islas.", price: 2500, hasOptions: false, options: [], available: true, hidden: false, sortOrder: 340, createdAt: now, updatedAt: now },
  { id: "extra-king-mustang-runa", type: "extra", title: "King Mustang Runa", description: "Mostaza con miel.", price: 2500, hasOptions: false, options: [], available: true, hidden: false, sortOrder: 350, createdAt: now, updatedAt: now },
  { id: "extra-salsa-alioli-runa", type: "extra", title: "Salsa Alioli Runa", description: "Mayonesa de ajo.", price: 2500, hasOptions: false, options: [], available: true, hidden: false, sortOrder: 360, createdAt: now, updatedAt: now },
];
